#服务端口
server:
  port: 8080
  servlet:
    context-path: /xmos
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#日志
logging:
  level:
    com.xmos: debug
#mybatis配置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.xmos.entity

